CREATE TABLE products (
    id SERIAL PRIMARY KEY,
    title VARCHAR(255) NOT NULL,
    description TEXT,
    price NUMERIC(10, 2) NOT NULL,
    stock INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    category VARCHAR(50) NOT NULL,
    brand TEXT,
    rating FLOAT8,
    discount_percentage FLOAT8,
    thumbnail TEXT,
    images JSONB NOT NULL,
    tags JSONB NOT NULL,
    reviews JSONB,
    minimum_order_quantity INTEGER DEFAULT 1,
    availability_status TEXT NOT NULL,
    return_policy VARCHAR(50) NOT NULL,
    warranty_information TEXT,
    shipping_information TEXT,
    dimensions JSONB,
    meta JSONB,
    sku TEXT,
    weight INTEGER NOT NULL
);