FROM rust:slim

RUN apt-get update && apt-get install -y \
    pkg-config \
    libssl-dev \
    libpq-dev \
    libpq5 \
    ca-certificates \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY Cargo.toml Cargo.lock ./
RUN mkdir src && echo "fn main() {}" > src/main.rs
RUN cargo build

RUN cargo install cargo-watch
RUN cargo install sqlx-cli --no-default-features --features postgres

COPY . .
RUN touch src/main.rs

EXPOSE 8000
CMD ["cargo-watch", "-x", "run"]

